// The shader build, without the file system: config in, file contents out.
// tools/build-shaders.mjs is the command that reads and writes the files.
//
// A config is (paths relative to the repo root):
//
//   {
//     "outputs": [
//       { "entry": "shaders/antisphere-raycast.wgsls",
//         "out": "public/gen/antisphere-raycast.wgsl",
//         "defines": { "SOME_FEATURE": true } }
//     ],
//     "layouts": "public/gen/layouts.js"
//   }
//
// Each output is its entry linked with everything it imports (see
// preprocess.js), under a do-not-edit header, with its source map as the
// last line (see public/shader-map.js). Each output's resources are given
// their bindings on the way (see bindings.js). The layouts module has a
// class for every struct any output shares with the host (see layout.js,
// emit-js.js), and BINDINGS, each output's bindings by name.

import { build, ShaderSourceError } from './preprocess.js';
import { sharedStructs, LayoutError } from './layout.js';
import { assignBindings, BindingError } from './bindings.js';
import { emitModule, emitBindings } from './emit-js.js';
import { mapLine } from '../../public/shader-map.js';

const TOOL = 'tools/build-shaders.mjs';

/** What BINDINGS calls an output: its file's name, less .wgsl. */
const outputName = (out) => out.slice(out.lastIndexOf('/') + 1).replace(/\.wgsl$/, '');

function wgslHeader(entry) {
  return [
    `// GENERATED by ${TOOL} from ${entry}; do not edit.`,
    '// Edit the files under shaders/ and run `npm run shaders`.',
  ];
}

/**
 * @param {object} config  as above
 * @param {(path: string) => string | Promise<string>} read  repo-relative
 * @param {object} [options]
 * @param {(message: string) => void} [options.warn]  where #warning goes;
 *        console.warn by default
 * @returns {Promise<{ path: string, content: string }[]>} every file to write
 */
export async function buildAll(config, read, { warn = console.warn } = {}) {
  const files = [];
  const shared = new Map();                 // struct name -> { layout, from }
  const bindings = {};                      // output name -> { slots, entries }

  for (const output of config.outputs) {
    const linked = await build(output.entry, { defines: output.defines ?? {}, read, warn });
    const { map } = linked;

    let code, structs;
    try {
      const assigned = assignBindings(linked.code);
      code = assigned.code;
      bindings[outputName(output.out)] = { slots: assigned.slots, entries: assigned.entries };
      structs = sharedStructs(code);
    } catch (e) {
      if (!(e instanceof LayoutError || e instanceof BindingError)) throw e;
      const at = mapLine(map, e.line);
      throw at ? new ShaderSourceError(at.path, at.line, e.message) : e;
    }
    for (const s of structs) {
      const seen = shared.get(s.name);
      if (seen && JSON.stringify(seen.layout) !== JSON.stringify(s)) {
        throw new Error(`struct ${s.name} is laid out differently in ${seen.from} and ${output.entry}; ` +
                        'one name must mean one layout, since both share one JS class');
      }
      if (!seen) shared.set(s.name, { layout: s, from: output.entry });
    }

    const header = wgslHeader(output.entry);
    const shifted = map.map((b) => ({ ...b, offset: b.offset + header.length }));
    files.push({
      path: output.out,
      content: `${header.join('\n')}\n${code}\n// sourcemap: ${JSON.stringify(shifted)}\n`,
    });
  }

  if (config.layouts) {
    const entries = config.outputs.map((o) => o.entry).join(', ');
    const header = [
      `// GENERATED by ${TOOL} from the structs shared by ${entries}; do not edit.`,
      '// Edit the structs under shaders/ and run `npm run shaders`. See',
      '// tools/shader-build/emit-js.js for what each class offers.',
    ].join('\n');
    files.push({ path: config.layouts,
                 content: emitModule([...shared.values()].map((s) => s.layout), header) + emitBindings(bindings) });
  }
  return files;
}
